spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insightguard?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

doubao:
  api:
    key: f5e3965e-5d25-4736-9137-1fdb7e0188ee
    url: https://ark.cn-beijing.volces.com/api/v3/chat/completions
  model:
    id: doubao-1-5-pro-32k-250115